from models import Domain, Idea

def create_idea(id, title, problem, target, ai, mvp, tech, moat, pricing, gtm, risks, advantage, domain_id, pain, weeks, market, complexity, why_ai=None):
    return Idea(
        id=id,
        title=title,
        problem=problem,
        target_customer=target,
        ai_use_case=ai,
        mvp_scope=mvp if isinstance(mvp, list) else [mvp],
        tech_stack=tech if isinstance(tech, list) else [tech],
        moat=moat,
        pricing_model=pricing,
        go_to_market=gtm if isinstance(gtm, list) else [gtm],
        risks=risks if isinstance(risks, list) else [risks],
        founder_advantage=advantage,
        why_ai=why_ai,
        domain_id=domain_id,
        pain_severity=pain,
        time_to_mvp_weeks=weeks,
        market_size_score=market,
        complexity_score=complexity
    )

DOMAINS_DATA = [
    Domain(id="b2b_saas", name="B2B SaaS", description="Solve boring problems for businesses. High stickiness, recurring revenue.", idea_count=5),
    Domain(id="dev_tools", name="Developer Tools / Inf", description="Sell shovels to the gold diggers. High technical barrier.", idea_count=5),
    Domain(id="ai_agents", name="AI Agents & Automation", description="Replace repetitive human workflows with autonomous agents.", idea_count=5),
    Domain(id="healthcare", name="Healthcare (Non-Diag)", description="Patient experience, admin & support. High trust required.", idea_count=5),
    Domain(id="education", name="Education / Skilling", description="Personalized learning & interview prep. High volume.", idea_count=5),
    Domain(id="fintech", name="Finance / Compliance", description="Money management & regulatory automation. High value.", idea_count=5),
    Domain(id="legal", name="Legal / Contracts", description="Automate paperwork & compliance. Localized heavily.", idea_count=5),
    Domain(id="sales_marketing", name="Sales / Marketing", description="Help businesses grow. Instant ROI demonstration.", idea_count=5),
    Domain(id="hr_hiring", name="HR / Hiring", description="Recruitment & employee experience. Deep workflow integration.", idea_count=5),
    Domain(id="customer_support", name="Customer Support", description="Deflect tickets & improve CSAT. High request volume.", idea_count=5),
]

IDEAS_DATA = [
    # --- DOMAIN 1: B2B SaaS ---
    create_idea(
        id="invoice_extraction",
        title="Invoice Data Extraction & Auto-Reconciliation for Indian SMBs",
        problem="Indian SMBs (manufacturers, distributors, retailers) receive 50-500 invoices/month in mixed formats (PDF, WhatsApp images, scanned docs). Accountants manually type data into Tally/Zoho Books, taking 2-5 min per invoice. Error rate ~15%. GST reconciliation is a monthly nightmare.",
        target="CA firms (50-200 SMB clients), trading companies, distributors with ₹5-50Cr revenue. 10-50 employee companies.",
        ai="Document AI (LayoutLM/Donut via HuggingFace) for OCR + structure extraction. GPT-4o-mini API for field normalization. Rule-based validation + fuzzy matching for vendor deduplication.",
        why_ai="Invoice formats are wildly inconsistent. Pure template matching breaks. Human-level understanding of 'total amount' vs 'taxable amount' vs 'CGST' in 47 different layouts requires vision-language models.",
        mvp=["WhatsApp bot + email forwarding endpoint", "Extract: vendor name, GSTIN, invoice number, date, line items, amounts, taxes", "Export to Excel + Tally XML", "Dashboard showing extraction confidence scores"],
        tech=["FastAPI backend (Railway/Render free tier)", "Donut-base model (self-hosted on Modal/Replicate pay-per-use)", "GPT-4o-mini for ambiguous cases (₹500/month budget)", "Supabase free tier for DB", "WhatsApp Business API (free tier)"],
        moat="Indian invoice format training data. Integration lock-in with Tally/Zoho. Switching cost = re-training accountant workflow.",
        pricing="₹999/month for 200 invoices, ₹2999 for 1000 invoices. Pay-per-invoice after limit (₹3/invoice). CA firms: ₹9999/month for unlimited (white-label dashboard for their clients).",
        gtm=["LinkedIn outreach to CAs in Tier-2 cities (less competitive)", "Offer free processing for first month", "WhatsApp group infiltration (CA communities)", "Cold email to Tally user lists (scraped from business directories)", "IndiaMART supplier contact lists"],
        risks=["Tally already has OCR features (but they suck)", "Adoption friction: 'My accountant likes manual entry'", "Payment collection from SMBs is HARD", "Accuracy needs to be 95%+ or they won't trust it"],
        advantage="You can out-ship Tally's innovation cycle (6-12 months). You can do personalized onboarding calls. You speak the language (Hindi/regional support).",
        domain_id="b2b_saas", pain=10, weeks=3, market=8, complexity=6
    ),
    create_idea(
        id="meeting_intel",
        title="Meeting Intelligence for Remote Indian Teams",
        problem="Indian IT services companies, BPOs, remote teams do 5-10 hours of Zoom/Meet calls daily. No one takes notes. Action items are forgotten. Clients complain about lack of follow-through. Managers waste time asking 'what was decided?'",
        target="IT services companies (20-200 employees), consulting firms, agencies. Decision maker: Project Manager / COO.",
        ai="Deepgram/AssemblyAI API for transcription (₹0.01/min). GPT-4o-mini for summarization, action item extraction, sentiment analysis. Speaker diarization for 'who said what'.",
        mvp=["Zoom/Meet bot that auto-joins meetings", "Real-time transcription + post-call summary", "Action items extracted with assignee names", "Slack/Email delivery of summary", "Simple dashboard for searching past meetings"],
        tech=["Recall.ai or Fireflies API (₹50/meeting hour) OR build custom Zoom bot", "Deepgram API", "GPT-4o-mini", "Postgres on Supabase", "Next.js frontend on Vercel"],
        moat="Workflow integration. Once embedded in daily standup routine, high stickiness. Custom terminology understanding (client names, project codenames).",
        pricing="₹4999/month for 50 hours of meetings (₹100/hour). Enterprise: ₹19,999/month unlimited + custom integrations.",
        gtm=["Offer free to 5 agencies for 1 month testimonials", "LinkedIn ads targeting 'Project Manager' + 'IT Services'", "Cold email to companies listed on Clutch.co India", "Post in Slack communities (GrowthX, Product management India)"],
        risks=["Otter.ai, Fireflies already exist (but expensive, US-focused)", "Privacy concerns (recordings stored)", "India price sensitivity: 'Why pay when Zoom has transcription?'", "Actually making people change behavior (use the summary) is hard"],
        advantage="India-specific pricing. Regional language support (Hinglish transcription). Tally/Zoho integration (Indian tool ecosystem).",
        domain_id="b2b_saas", pain=7, weeks=4, market=6, complexity=5
    ),
    create_idea(
        id="rfp_automation",
        title="RFP Response Automation for Government Tenders",
        problem="Indian SMBs bidding for government tenders (GeM, state procurement) spend 20-40 hours per RFP. 80% of the content is copy-paste from past bids. Win rate <10%. Missing a compliance checkbox = instant rejection.",
        target="Mid-sized contractors (construction, IT, stationery, services), consultants who bid on 10-50 tenders/year. ₹5-50Cr revenue companies.",
        ai="PDF parsing of tender documents (30-200 pages). RAG over past successful bids. GPT-4o for draft generation (technical specs, compliance sections). Checklist generator for mandatory attachments.",
        mvp=["Upload tender PDF", "AI extracts: requirements, evaluation criteria, deadlines", "Auto-generate response draft using past bid library", "Compliance checklist (what documents to attach)", "Export to Word/PDF"],
        tech=["PyMuPDF for extraction", "Pinecone/Qdrant for vector DB (free tier 1GB)", "GPT-4o-mini (₹2000/month)", "Flask/FastAPI on Render", "Simple React frontend"],
        moat="Proprietary library of winning bids. Domain expertise (GeM terminology). Integration with e-procurement portals (data scraping).",
        pricing="₹9999/tender processed. Or ₹29,999/month for 5 tenders. Enterprise: ₹99,999/year + rev share on wins.",
        gtm=["Direct call companies listed as vendors on GeM portal", "Attend MSME networking events", "LinkedIn outreach to 'Business Development' folks in construction/IT", "Partner with CA firms who help with financial compliance"],
        risks=["Low volume market (each customer bids 10-50x/year only)", "Requires significant domain expertise to not hallucinate compliance", "GeM portal is clunky but free (substitution risk)", "Corruption/relationships matter more than bid quality"],
        advantage="You can deeply specialize in 1-2 tender types. You can offer hand-holding (not just software). Low competition (unsexy problem).",
        domain_id="b2b_saas", pain=9, weeks=4, market=5, complexity=7
    ),
    create_idea(
        id="contract_clause_check",
        title="Contract Clause Extraction & Risk Flagging for Indian Businesses",
        problem="Indian SMBs sign vendor contracts, supplier agreements, customer MSAs without legal review (₹50k+ per contract for lawyer). Hidden liability clauses, auto-renewal terms, penalty clauses cause ₹5L-₹50L losses later.",
        target="Startups (pre-Series A), growing SMBs, import/export businesses, IT services companies. Decision maker: Founder/CFO.",
        ai="PDF extraction + chunking. GPT-4o prompted to identify: liability caps, termination clauses, payment terms, IP ownership, dispute resolution, auto-renewal. Risk scoring based on clause severity. Comparison to 'standard' contract templates.",
        mvp=["Upload contract PDF (5-50 pages)", "AI highlights risky clauses with explanation", "Risk score (1-10)", "Suggested redlines / negotiation points", "Export report"],
        tech=["PyMuPDF", "GPT-4o-mini (₹1500/month for 50 contracts)", "LangChain for structured extraction", "Streamlit frontend", "Supabase for storage"],
        moat="Indian legal terminology training. Library of annotated contracts. Integration with DocuSign/contract workflows.",
        pricing="₹999 per contract review. ₹9999/month for 15 contracts. Enterprise: ₹49,999/year + unlimited reviews.",
        gtm=["Cold email to YourStory/Inc42 startup database", "Post in founder Slack groups (LetsVenture, Headstart)", "Partner with startup accelerators", "LinkedIn ads targeting 'Founder' + 'Legal'"],
        risks=["Liability concern: 'AI said clause was fine, now I'm sued'", "Low purchase frequency (sign 5-20 contracts/year)", "Requires legal accuracy (one mistake = reputation destroyed)", "SpotDraft/Contractzy already exist (but expensive)"],
        advantage="You can offer freemium (3 contracts free). You can do synchronous review calls. Rapid iteration on edge cases.",
        domain_id="b2b_saas", pain=8, weeks=3, market=6, complexity=6
    ),
    create_idea(
        id="expense_verification",
        title="Employee Expense Report Auto-Verification for Indian SMBs",
        problem="Employees submit expense reports (travel, client meetings, supplies) with 5-20 receipts/month. Finance teams manually check: valid GST number, category matches claim, amount matches receipt. 30-60 min per employee/month. Fraud is common (fake bills, inflated amounts).",
        target="Indian SMBs with 50-500 employees, distributed sales teams. Decision maker: CFO/Finance Manager.",
        ai="OCR for receipt extraction (date, vendor, amount, GST, category). GSTIN validation via govt API. Policy engine (check if expense within limits). Anomaly detection (duplicate bills, suspicious patterns).",
        mvp=["Mobile app for employee to snap receipt", "Auto-extract fields", "Flag policy violations", "Finance dashboard to approve/reject", "Export to Zoho Expense/Tally"],
        tech=["Donut/TrOCR for receipt OCR", "GPT-4o-mini for ambiguous field extraction", "React Native (Expo) for mobile", "FastAPI backend on Railway", "Postgres on Supabase"],
        moat="Integration with Indian payroll systems (Razorpay, GreytHR). Historical fraud patterns. Workflow lock-in.",
        pricing="₹199/employee/month. 50-employee company = ₹9950/month. Annual plans: 20% discount.",
        gtm=["Cold email to CFOs (from Crunchbase India)", "Partner with payroll providers (GreytHR, Keka)", "LinkedIn ads targeting 'Finance Manager'", "Offer 30-day free trial with full fraud report"],
        risks=["Zoho Expense exists (but UI is terrible, no AI)", "Requires high accuracy (false positives = angry employees)", "Indian SMBs resistant to per-employee pricing", "Payment collection challenge"],
        advantage="You can build for Indian receipt formats (not US formats). You can offer white-glove onboarding. Rapid feature iteration.",
        domain_id="b2b_saas", pain=7, weeks=4, market=7, complexity=6
    ),
    # --- DOMAIN 2: Developer Tools / AI Infra ---
    create_idea(
        id="rag_pipeline",
        title="One-Click RAG Pipeline for Non-AI Developers",
        problem="Indian startups/agencies want to add 'AI chat on your docs' but don't have ML engineers. Hiring ML freelancer = ₹50k-₹2L. LangChain tutorials are overwhelming. Vector DBs, embeddings, chunking strategies confuse non-experts.",
        target="Early-stage startups, dev agencies, solo SaaS founders. Technical audience but not ML specialists.",
        ai="Pre-configured RAG pipeline templates. Auto-chunking, embedding (text-embedding-ada-002), Pinecone setup. Prompt template library. Monitoring dashboard (latency, cost, hallucination detection).",
        mvp=["CLI tool: `rag-cli init`, upload docs, get API endpoint", "Support PDF, txt, docx", "Pre-built React component for chat UI", "Hosted backend (you manage infra)", "Usage analytics dashboard"],
        tech=["Python CLI (Click/Typer)", "LangChain", "Pinecone free tier (1GB) / Qdrant", "GPT-4o-mini", "FastAPI backend on Modal (pay-per-use)", "React component library"],
        moat="Developer experience. Template marketplace. Ecosystem (integrations with Notion, Confluence, Zendesk).",
        pricing="Free tier: 1000 queries/month. Pro: ₹4999/month (10k queries). Enterprise: ₹19,999/month (100k queries) + custom models.",
        gtm=["Dev.to / Hashnode tutorial ('Build ChatGPT for your docs in 5 minutes')", "GitHub README with demo", "IndiaFOSS / PyCon India talk", "Cold DM to YC India startups", "ProductHunt launch"],
        risks=["LangChain, LlamaIndex already do this (but complex)", "Vercel AI SDK, Chatbase exist (competitors)", "Commoditization risk (everyone will copy)", "Developers want control, not abstraction"],
        advantage="You know the pain. You can create India-specific tutorials (Hindi docs, Indic language support). Fast iteration on DX.",
        domain_id="dev_tools", pain=8, weeks=3, market=7, complexity=6
    ),
    create_idea(
        id="llm_cost_monitoring",
        title="LLM Cost Monitoring & Optimization for Indian Startups",
        problem="Indian startups using OpenAI/Anthropic APIs see bills jump from $50 to $2000/month unpredictably. No visibility into: which features burn money, which users cause loops, prompt efficiency. CFOs panic when AWS bill arrives.",
        target="Seed to Series A startups using LLM APIs. 5-50 person tech teams. Decision maker: CTO/Eng Lead.",
        ai="Log ingestion (OpenAI API call metadata). Token usage analytics per user/feature/model. Prompt efficiency scoring (output tokens vs completion quality). Anomaly detection (runaway loops, abuse). Cost forecasting.",
        mvp=["SDK: wrap OpenAI client, send metadata to your backend", "Dashboard: cost breakdown by endpoint, user, time", "Alerts: budget thresholds, unusual spikes", "Recommendations: switch to GPT-4o-mini for X% of calls"],
        tech=["Python SDK (wraps OpenAI client)", "FastAPI for log ingestion", "TimescaleDB on Supabase (time-series data)", "Next.js dashboard on Vercel", "Prometheus-style metric aggregation"],
        moat="Data network effects (more customers = better benchmarks). Integration depth (automatic A/B testing of prompts).",
        pricing="Free tier: <$500 LLM spend/month. Pro: ₹4999/month. Enterprise: ₹19,999/month + dedicated Slack channel.",
        gtm=["Post in LangChain Discord, r/LangChain", "LinkedIn outreach to Indian CTOs", "Write blog: 'We cut our OpenAI bill by 60%'", "Cold email to YC startups using AI", "Partner with AI dev agencies"],
        risks=["OpenAI usage dashboard already exists (basic)", "Helicone, LangSmith exist (US-focused, expensive)", "Requires SDK integration (friction)", "Market size limited (only AI-using startups)"],
        advantage="India pricing. Focus on seed-stage (underserved). You can do manual optimization consulting alongside.",
        domain_id="dev_tools", pain=9, weeks=3, market=6, complexity=5
    ),
    create_idea(
        id="govt_forms_copilot",
        title="GitHub Copilot for Indian Government Forms",
        problem="Indian developers building govt-facing products (fintech, healthtech, B2G SaaS) spend 40-60 hours per integration: Aadhaar XML signing, GST API, DigiLocker, UPI, etc. Documentation is terrible. StackOverflow has 3 outdated answers.",
        target="Indian dev agencies, fintech startups, B2G SaaS companies. Decision maker: Eng Lead / Founder.",
        ai="VSCode extension: autocomplete for govt APIs. Code snippet library (copy-paste ready). AI answers trained on UIDAI, GSTN, NPCI docs. Debugging assistant (parse govt API error messages).",
        mvp=["VSCode extension with snippet library", "Chat interface for 'how to integrate Aadhaar eKYC'", "20-30 code templates (Python, Node.js)", "Search across govt documentation"],
        tech=["VSCode extension (TypeScript)", "RAG over govt docs (PDF scraping)", "GPT-4o-mini for Q&A", "GitHub repo for snippet library", "Simple web dashboard"],
        moat="Proprietary snippet library. Community contributions (like StackOverflow but Indian govt APIs). First-mover in niche.",
        pricing="Freemium: 10 queries/month. Pro: ₹999/developer/month. Enterprise: ₹9999/month for 15 devs + priority support.",
        gtm=["Post in IndiaStack Slack, HasGeek forums", "Demo at fintech meetups (Bangalore, Mumbai)", "Cold email to PeLocal, Setu API customers", "Blog: 'Integrate Aadhaar in 10 minutes'", "ProductHunt India launch"],
        risks=["Low TAM (only B2G developers)", "Govt APIs change frequently (maintenance hell)", "Free tutorials on YouTube sufficient", "Requires continuous content updates"],
        advantage="You've suffered through this. You can maintain active Slack community. Rapid iteration on new APIs (UPI 2.0, ABDM).",
        domain_id="dev_tools", pain=9, weeks=4, market=5, complexity=7
    ),
    create_idea(
        id="test_data_gen",
        title="Automated Test Data Generation for Indian Apps",
        problem="QA teams testing Indian apps (fintech, edtech, SaaS) need realistic test data: Indian names, phone numbers, PANs, Aadhaar, addresses, pincodes. Current tools generate 'John Doe, 90210' (USA data). Manually creating 1000 test users = 5 hours.",
        target="Indian SaaS companies, dev agencies, product teams. 20-500 employees. Decision maker: QA Lead / Eng Manager.",
        ai="LLM generates realistic Indian names (regional distribution). Rule-based generation of valid PAN, Aadhaar (fake but format-valid). Pincode-aware address generation. Biased distributions (more Mumbai users than Imphal).",
        mvp=["Web UI: specify schema (name, phone, city, PAN, etc.)", "Generate 10-10k records", "Export as JSON, CSV, SQL", "API for programmatic access", "'Smart' mode: relationships (family members, same address)"],
        tech=["FastAPI backend", "GPT-4o-mini for name/address generation", "Python Faker library (extended for India)", "React frontend", "Postgres for data storage"],
        moat="Indian data quality. Integration with Postman, Selenium. Compliance-aware (GDPR-safe fake data).",
        pricing="Free: 100 records/month. Pro: ₹1999/month (10k records). Enterprise: ₹9999/month (unlimited) + custom schemas.",
        gtm=["Post in QA Slack groups, Testing communities", "Cold email to QA Leads (from LinkedIn)", "Blog: 'Stop using US test data in Indian apps'", "Integration with BrowserStack, LambdaTest", "Sponsor testing conferences"],
        risks=["Faker library + manual scripts 'good enough'", "Privacy concerns (even though fake data)", "Narrow use case (only testing)", "Hard to communicate value ($2k/year for test data?)"],
        advantage="Deep understanding of Indian data nuances. You can create templates for specific industries (fintech, edtech). Fast feature iteration.",
        domain_id="dev_tools", pain=7, weeks=2, market=6, complexity=4
    ),
    create_idea(
        id="api_docs_gen",
        title="API Documentation Auto-Generator from Codebase",
        problem="Indian dev agencies deliver APIs to clients with zero/outdated docs. Developers manually write Swagger/Postman collections, taking 10-20 hours per project. Client onboarding delayed. Support tickets ('How do I call this endpoint?') explode.",
        target="Dev agencies, B2B SaaS companies, API-first startups. 10-100 employees. Decision maker: Eng Lead.",
        ai="Parse codebase (FastAPI, Express.js, Django). Extract routes, parameters, response schemas. GPT-4o generates: descriptions, examples, error cases. Auto-create Postman collection + Swagger YAML.",
        mvp=["CLI tool: `docgen init`, scan codebase", "Support FastAPI, Express, Flask", "Generate markdown docs + Swagger UI", "One-click deploy to GitHub Pages", "Versioning support"],
        tech=["Python AST parsing (for FastAPI/Flask)", "TypeScript AST for Express.js", "GPT-4o-mini for descriptions", "CLI tool (Click)", "Static site generator (Docusaurus)"],
        moat="Codebase understanding depth. Integration with CI/CD (auto-update docs). Multi-language support.",
        pricing="Open-source core. Paid: ₹4999/month for hosted docs + search + versioning + analytics. Enterprise: ₹19,999/month + SSO + custom branding.",
        gtm=["GitHub README + demo video", "Post in r/webdev, r/nodejs, r/django", "Dev.to tutorial", "Cold email to YC companies", "ProductHunt launch"],
        risks=["Swagger-codegen, FastAPI auto-docs exist", "Developers prefer manual control", "Code parsing is brittle (breaks on edge cases)", "OSS competition"],
        advantage="You know the pain from agency work. You can support Indian frameworks (custom Django patterns). Rapid bug fixes.",
        domain_id="dev_tools", pain=8, weeks=3, market=7, complexity=6
    ),

    # --- DOMAIN 3: AI Agents & Automation ---
    create_idea(
        id="restaurant_bot",
        title="WhatsApp Bot for Restaurant Order Management",
        problem="Indian restaurants get 50-200 orders/day via WhatsApp. Staff manually: confirm order, check inventory, update kitchen display, send payment link, track delivery. Orders get lost in chat history. Missed orders = ₹5k-₹20k daily revenue loss.",
        target="Cloud kitchens, small restaurant chains (5-20 outlets), QSRs. Bangalore, Mumbai, Delhi NCR. Decision maker: Owner / Ops Manager.",
        ai="NLU to parse order message ('2 butter chicken, 1 naan'). Menu matching (fuzzy, handles typos). Inventory check integration. Auto-reply with order confirmation + total. Integration with Swiggy/Zomato for reconciliation.",
        mvp=["WhatsApp Business API integration", "Parse incoming orders (text messages)", "Send confirmation + payment link (Razorpay)", "Dashboard: today's orders, revenue", "Kitchen display (real-time order queue)"],
        tech=["WhatsApp Business API (₹500-₹2000/month)", "FastAPI backend on Railway", "GPT-4o-mini for ambiguous orders", "Razorpay API", "React dashboard on Vercel"],
        moat="Menu training data. Integration with POS systems (Petpooja, PosBytz). Workflow lock-in (staff trained on your system).",
        pricing="₹2999/month per outlet + ₹2/order processed. 100 orders/day = ₹8999/month total.",
        gtm=["Walk into cloud kitchens in Koramangala, Gurgaon", "Offer 1-month free trial", "Partner with cloud kitchen aggregators (Rebel Foods franchisees)", "Instagram ads targeting restaurant owners", "Food blogger partnerships"],
        risks=["Dotpe, Thrive, UrbanPiper exist (but expensive, clunky)", "Restaurants churn fast (industry instability)", "WhatsApp policy changes (API restrictions)", "Staff resistance ('We prefer manual')"],
        advantage="You can do in-person onboarding. Hyderabad restaurant network. You can customize per cuisine (South Indian menu patterns).",
        domain_id="ai_agents", pain=9, weeks=3, market=8, complexity=5
    ),
    create_idea(
        id="email_triage_agent",
        title="Email Triage Agent for Customer Support",
        problem="Indian B2B SaaS companies, agencies, e-commerce get 100-500 support emails/day. Support agents spend 30% of time reading, categorizing, routing. SLA breaches on urgent issues. Common queries (password reset, billing) answered manually 50x/day.",
        target="Indian SaaS startups, e-commerce (D2C), B2B service companies. 20-200 employees. Decision maker: Support Lead / COO.",
        ai="Email classification (urgent/normal, category: billing/technical/sales). Auto-response for common queries (password reset, tracking). Priority scoring (angry customer, high-value account). Ticket routing to right agent. Sentiment analysis.",
        mvp=["Gmail/Outlook plugin", "Auto-label incoming emails", "Draft responses for common queries (human approves)", "Priority inbox view", "Analytics: response time, volume by category"],
        tech=["Gmail API / Outlook Graph API", "GPT-4o-mini for classification + drafting", "LangChain for email parsing", "Postgres on Supabase", "Chrome extension for UI"],
        moat="Historical ticket training data. Integration with Freshdesk/Zoho Desk. Customer-specific language patterns.",
        pricing="₹4999/month for 1000 emails. ₹9999/month for 5000 emails. Enterprise: ₹29,999/month unlimited + Slack integration.",
        gtm=["Cold email to Support Leads (from LinkedIn)", "Free trial: 'We'll triage your backlog for free'", "Post in SaaS founder groups", "Partner with Freshdesk/Zoho (app marketplace)", "Case study with 1-2 beta customers"],
        risks=["Zendesk, Freshdesk have AI features (but bad)", "Accuracy concerns (routing to wrong team)", "Integration friction (need email access)", "Support teams resist automation (job security fears)"],
        advantage="You can customize for Indian business language (Hindi, code-switching). You can do white-glove setup. Rapid iteration on edge cases.",
        domain_id="ai_agents", pain=8, weeks=3, market=7, complexity=6
    ),
    create_idea(
        id="linkedin_outreach_agent",
        title="LinkedIn Outreach Agent for B2B Sales",
        problem="Indian B2B SaaS founders, agencies do LinkedIn outreach manually. Finding 50 leads = 2 hours. Writing personalized messages = 1 hour. 2-3% reply rate. Hiring SDR = ₹30k-₹50k/month.",
        target="Early-stage B2B founders, dev agencies, consultants, recruiters. Decision maker: Founder / Sales Lead.",
        ai="Scrape LinkedIn Sales Navigator (via API/automation). Score leads (based on profile, activity, likelihood to respond). Generate personalized messages (GPT-4o-mini). Auto-send connection requests + follow-up sequence. Track responses, book meetings.",
        mvp=["Chrome extension: scrape LinkedIn profiles", "Lead scoring (simple model: title, company size, activity)", "Message template library + AI personalization", "Auto-schedule: 10 requests/day (to avoid bans)", "Dashboard: sent, accepted, replied"],
        tech=["Chrome extension (Puppeteer for automation)", "GPT-4o-mini for message generation", "Supabase for data storage", "Next.js dashboard", "Calendly integration for booking"],
        moat="Anti-ban techniques. Message template A/B testing. Integration with CRM (Pipedrive, HubSpot).",
        pricing="₹4999/month for 200 leads/month. ₹9999/month for 500 leads. Enterprise: ₹29,999/month + unlimited + team seats.",
        gtm=["Use the tool on yourself (meta)", "Post in founder Slack groups", "LinkedIn ads (ironically)", "Cold outreach to agencies", "Productize case study ('50 leads in 1 week')"],
        risks=["LinkedIn bans accounts (biggest risk)", "Dripify, Expandi, Lemlist exist (competitors)", "Spam reputation (people hate cold LinkedIn)", "Requires constant cat-and-mouse with LinkedIn"],
        advantage="India-specific message templates. You know the founder pain. You can offer manual QA (review messages before send).",
        domain_id="ai_agents", pain=8, weeks=2, market=7, complexity=5
    ),
    create_idea(
        id="inventory_reorder_agent",
        title="Inventory Reorder Agent for Small Retailers",
        problem="Kirana stores, pharmacies, small retailers manually track stock. Run out of popular items → lost sales. Over-order → capital locked, expiry. Supplier WhatsApp groups chaotic. Reordering = 1-2 hours/week.",
        target="Kirana stores, pharmacies, hardware stores. 1-5 employee businesses. Tier-2/3 cities. Decision maker: Owner.",
        ai="Sales tracking (from billing software / manual entry). Demand forecasting (time-series). Reorder point calculation. Auto-generate WhatsApp message to supplier. Price comparison across suppliers.",
        mvp=["WhatsApp bot for retailer: 'Send today's sales'", "Track inventory levels", "Alerts: 'Low stock on Maggi, reorder 10 boxes'", "One-tap reorder via WhatsApp to supplier", "Simple web dashboard"],
        tech=["WhatsApp Business API", "Time-series forecasting (Prophet / statsmodels)", "FastAPI backend", "Postgres on Supabase", "React dashboard"],
        moat="Supplier network effects. Local language support. Integration with billing systems (Marg ERP, Tally).",
        pricing="₹499/month per store. Or ₹5/reorder transaction. Distributor model: ₹9999/month for 30 stores.",
        gtm=["Walk into kiranas in Hyderabad neighborhoods", "Offer 2-month free trial", "Partner with FMCG distributors (they push to retailers)", "WhatsApp group infiltration (retailer communities)", "Referral program (₹500 per store referred)"],
        risks=["Low digital literacy (owner can't use app)", "WhatsApp dependency (policy changes)", "Low willingness to pay (₹499 = 2 days profit)", "Udaan, JioMart already solving this (but complex)"],
        advantage="You can do in-person onboarding. Telugu/Hindi support. You can start hyper-local (one neighborhood).",
        domain_id="ai_agents", pain=9, weeks=4, market=8, complexity=6
    ),
    create_idea(
        id="social_auto_responder",
        title="Social Media Auto-Responder for Small Brands",
        problem="Indian D2C brands, local restaurants, service businesses get 50-200 DMs/comments daily on Instagram/FB. Questions: 'Price?', 'Delivery to X?', 'Is this veg?'. 30-40% go unanswered. Lost sales = ₹20k-₹1L/month.",
        target="D2C brands (beauty, fashion, food), local service businesses (salons, gyms, tutors). 1-20 employees. Decision maker: Owner / Marketing Manager.",
        ai="Scrape Instagram/FB DMs + comments. Answer common FAQs (price, delivery, ingredients). Escalate to human (complex queries, complaints). Auto-like comments, thank customers.",
        mvp=["Instagram/FB integration (via official APIs)", "FAQ knowledge base (10-20 Q&As)", "Auto-respond to DMs (with human approval mode)", "Dashboard: unanswered, escalated", "Analytics: response rate, conversion"],
        tech=["Instagram Graph API / FB Messenger API", "GPT-4o-mini for response generation", "FastAPI backend", "Supabase for data", "Next.js dashboard"],
        moat="Instagram/FB integration depth. Brand voice training. E-commerce integration (send product links).",
        pricing="₹2999/month for 500 messages. ₹6999/month for 2000 messages. Enterprise: ₹19,999/month + multiple pages.",
        gtm=["Instagram DM to D2C brands (meta)", "Cold email to brands on Shopify India", "Post in D2C founder groups", "Partner with Instagram influencer agencies", "Free for first 10 brands (case studies)"],
        risks=["ManyChat, Chatfuel exist (but not India-focused)", "API rate limits / policy changes", "Brand voice concerns ('AI sounds robotic')", "Need human in loop (not fully automated)"],
        advantage="India pricing. Hinglish support. You can do brand voice training calls. Fast iteration on Indian shopping behaviors.",
        domain_id="ai_agents", pain=7, weeks=2, market=7, complexity=4
    ),
    # --- DOMAIN 4: Healthcare (non-diagnostic first) ---
    create_idea(
        id="medical_report_summary",
        title="Medical Report Summarizer for Patients",
        problem="Indian patients get 5-20 page pathology/radiology reports in medical jargon. They don't understand 'lymphocytes elevated' or 'hepatomegaly noted'. Google search = panic. Waiting for doctor appointment to explain = 3-7 days.",
        target="Patients (B2C), health-conscious middle class, elderly with chronic conditions. Urban India.",
        ai="OCR for scanned reports. Medical term extraction + explanation. Risk flagging (values outside normal range). Suggested questions to ask doctor. Trend analysis (compare to past reports).",
        mvp=["Mobile app: snap photo of report", "Extract key findings", "Plain English summary", "Highlight abnormal values", "'What to ask your doctor' section"],
        tech=["Donut/TrOCR for medical report OCR", "GPT-4o-mini for summarization", "Medical terminology database (SNOMED CT open source)", "React Native app", "Supabase backend"],
        moat="Indian lab format training. User history (longitudinal tracking). Doctor network (referrals).",
        pricing="Freemium: 2 reports/month. Pro: ₹199/month (unlimited reports + trends). Family: ₹499/month (4 users).",
        gtm=["App store optimization (ASO)", "Instagram ads targeting 30-55 age group", "Partner with diagnostic labs (offer free to their customers)", "Content marketing (YouTube: 'Understanding your blood report')", "Doctor referrals (they recommend to patients)"],
        risks=["Liability ('AI misinterpreted my report')", "Regulatory (medical device classification?)", "Low repeat usage (get reports 2-4x/year)", "Trust ('Can I rely on AI for health?')"],
        advantage="Deep care in disclaimers. Indian report format expertise. You can add Telugu language support. Community building (health forums).",
        domain_id="healthcare", pain=9, weeks=3, market=8, complexity=6
    ),
    create_idea(
        id="clinical_doc_assistant",
        title="Clinical Documentation Assistant for Indian Doctors",
        problem="Indian doctors (private practice, small clinics) see 30-80 patients/day. Spend 30-60 min/day typing notes, prescriptions, follow-up instructions. EMR systems (Practo, Lybrate) clunky. Documentation = burnout.",
        target="Private practice doctors, small clinic chains (5-20 doctors). Specialties: General Medicine, Pediatrics, Dermatology. Decision maker: Doctor / Clinic Owner.",
        ai="Voice-to-text (Deepgram/Whisper). Medical transcription (doctor-patient conversation). Auto-generate: SOAP notes, diagnosis, prescription draft. ICD-10 code suggestion. Next appointment reminder draft.",
        mvp=["Mobile app for doctor", "Record consultation (audio)", "Auto-generate notes (editable)", "Export to EMR (PDF/text)", "Simple patient history lookup"],
        tech=["Whisper API for transcription", "GPT-4o-mini for note structuring", "React Native app", "Supabase for data", "HIPAA-compliant hosting (if needed)"],
        moat="Indian medical terminology (Hindi/regional terms). EMR integrations (Practo API). Doctor network effects.",
        pricing="₹999/month per doctor. Clinic (5-20 doctors): ₹7999/month. Enterprise (hospital): custom pricing.",
        gtm=["Cold call to private clinics", "Medical conference demos (IMA, API conferences)", "Partner with Practo, Lybrate", "Doctor WhatsApp groups", "Free for first 20 doctors (testimonials)"],
        risks=["Privacy concerns (patient data on cloud)", "Accuracy needs to be 98%+ (medical liability)", "Doctor adoption friction (learning new tool)", "Suki.ai, Nuance exists (but not India-focused)"],
        advantage="India pricing. Regional language support. You can do in-clinic demos. Iterative improvement with doctor feedback.",
        domain_id="healthcare", pain=9, weeks=4, market=7, complexity=6
    ),
    create_idea(
        id="no_show_predictor",
        title="Appointment No-Show Predictor & Reminder for Clinics",
        problem="Indian clinics, dental practices, physiotherapy centers have 20-30% no-show rate. Lost revenue = ₹50k-₹2L/month. Manual reminder calls = 1-2 hours/day. Patients forget, double-book, or just flake.",
        target="Private clinics, dental practices, diagnostic centers. 1-10 doctors. Decision maker: Clinic Manager / Owner.",
        ai="No-show prediction (based on: history, appointment time, day, weather). Smart reminder cadence (more reminders for high-risk patients). WhatsApp/SMS automated reminders. Waitlist management (auto-fill from waitlist).",
        mvp=["Clinic dashboard: today's appointments", "No-show risk score per patient", "Auto-send WhatsApp reminders (24 hrs + 2 hrs before)", "Waitlist: if cancellation, auto-offer slot", "Analytics: no-show rate trends"],
        tech=["Scikit-learn (simple classification model)", "WhatsApp Business API", "FastAPI backend", "Postgres on Supabase", "React dashboard"],
        moat="Historical no-show data. Integration with appointment systems. Local insights (monsoon = higher no-show).",
        pricing="₹2999/month per clinic + ₹2/reminder sent. Or ₹4999/month unlimited.",
        gtm=["Cold call to clinics", "Demo at medical conferences", "Partner with clinic management software (Doxper, Lybrate)", "WhatsApp group infiltration", "Case study: 'Reduced no-shows by 40%'"],
        risks=["Calendly, Zocdoc have reminder features (but not prediction)", "Low willingness to pay (₹3k/month = 6-10 appointments)", "WhatsApp dependency", "Model accuracy needs to be good (false positives = annoying patients)"],
        advantage="You can manually call high-risk patients initially (hybrid model). Local clinic network. Rapid iteration on reminder templates.",
        domain_id="healthcare", pain=7, weeks=3, market=6, complexity=5
    ),
    create_idea(
        id="drug_interaction_check",
        title="Medicine Interaction Checker for Indian Pharmacies",
        problem="Indian pharmacies dispense 100-500 prescriptions/day. 5-10% have drug interactions (patient takes multiple meds from different doctors). Pharmacists miss interactions (high volume, no time). Patient side effects = serious harm.",
        target="Independent pharmacies, pharmacy chains. Decision maker: Pharmacy Owner / Store Manager.",
        ai="OCR for prescription reading. Drug interaction database lookup. Allergy check (if patient history available). Dosage verification. Alert system for pharmacist.",
        mvp=["Tablet app for pharmacist", "Scan prescription (camera)", "Extract medicine names", "Check interactions (database lookup)", "Red flag: severe interactions", "Yellow flag: consult doctor"],
        tech=["TrOCR for prescription OCR", "Drug interaction database (OpenFDA / Indian Pharmacopoeia)", "React Native app", "Supabase backend", "Offline mode (local DB)"],
        moat="Indian medicine name database (brand to generic mapping). Integration with billing systems. Regulatory compliance.",
        pricing="₹1999/month per pharmacy. Chain (10+ stores): ₹15,999/month.",
        gtm=["Walk into pharmacies (Hyderabad, Bangalore)", "Free trial: 2 months", "Partner with pharmacy chains (Apollo, MedPlus)", "Medical rep partnerships", "IPA (Indian Pharmacy Association) outreach"],
        risks=["Liability (missed interaction = lawsuit)", "Pharmacists don't have time (1-2 min per prescription)", "OCR accuracy on handwritten prescriptions (messy)", "Low willingness to pay (pharmacies have thin margins)"],
        advantage="You can curate Indian medicine database manually. You can do in-person training. Iterative improvement on OCR (handwriting patterns).",
        domain_id="healthcare", pain=9, weeks=4, market=7, complexity=7
    ),
    create_idea(
        id="chronic_disease_assistant",
        title="Chronic Disease Self-Management Assistant",
        problem="Indian diabetics, hypertensives, thyroid patients manage conditions poorly. Forget meds, don't track vitals, miss follow-ups. Hospital readmissions = ₹50k-₹2L. Doctors can't micro-manage 500 patients.",
        target="B2C: patients with chronic conditions. B2B: hospitals, insurance companies (reduce readmissions).",
        ai="Med reminder (smart: based on meal time, travel). Vitals tracking (BP, sugar, weight). Trend analysis + alerts (sugar consistently high). Lifestyle tips (personalized: exercise, diet). Teleconsult triggers (when to see doctor).",
        mvp=["Mobile app", "Daily med reminders", "Log vitals (manual entry / photo of glucometer)", "Simple charts (trends)", "Personalized tips (GPT-4o-mini based on data)"],
        tech=["React Native app", "GPT-4o-mini for tip generation", "Time-series analysis (simple rules + Prophet)", "Supabase backend", "Push notifications"],
        moat="Longitudinal user data. Doctor partnerships. Integration with wearables (if later).",
        pricing="Freemium: basic reminders. Pro: ₹299/month (insights + tips). Hospital B2B: ₹10/patient/month.",
        gtm=["App store optimization (ASO)", "Doctor referrals (give pamphlets to doctors)", "Partner with insurance (prevent claims)", "Content: YouTube diabetes management tips", "Community building (WhatsApp support groups)"],
        risks=["Low retention (people stop logging after 2 weeks)", "Wearable competition (Apple Watch, Fitbit)", "Privacy concerns (health data)", "Willingness to pay (health app fatigue)"],
        advantage="Deep empathy (if you/family have condition). Indian diet/lifestyle context. You can build community (not just app). Iterative engagement loops.",
        domain_id="healthcare", pain=8, weeks=4, market=8, complexity=6
    ),

    # --- DOMAIN 5: Education / Skilling ---
    create_idea(
        id="interview_prep",
        title="Personalized Interview Prep for Indian Job Seekers",
        problem="Indian college students, job switchers practice interviews poorly. Generic LeetCode grinding. Don't practice behavioral questions. Mock interview platforms expensive (₹2k-₹5k per session). Placement season = 1000 rejects → 1 offer.",
        target="College students (Tier-2/3 engineering), job switchers (2-5 YOE), bootcamp grads. Decision maker: Student / Job seeker.",
        ai="Resume analysis (identify weak points). Generate tailored interview questions (based on resume, job description). AI interviewer (voice-based mock interview). Answer evaluation (technical correctness, communication). Improvement suggestions.",
        mvp=["Web app: upload resume + job description", "Get 10 personalized questions", "Text-based mock interview", "Answer feedback (score + suggestions)", "Progress tracking"],
        tech=["GPT-4o-mini for question generation + evaluation", "FastAPI backend", "Next.js frontend", "Supabase for user data", "(Later: voice with Deepgram)"],
        moat="Personalization depth. Indian company interview patterns. Progress tracking data.",
        pricing="Freemium: 5 questions/month. Pro: ₹499/month (unlimited). Interview season pass: ₹1999 (3 months).",
        gtm=["Reddit (r/Indian_Academia, r/developersIndia)", "College placement cell partnerships", "LinkedIn posts targeting final year students", "YouTube: 'Top 10 interview mistakes'", "Referral program (₹100 off per referral)"],
        risks=["Pramp, Interviewing.io exist (but US-focused, expensive)", "Students won't pay (broke)", "Quality of AI feedback (will they trust it?)", "High churn (use only during job search)"],
        advantage="You know Indian interview patterns (TCS, Infosys, startups). You can build community (Discord for practice partners). India pricing.",
        domain_id="education", pain=8, weeks=3, market=7, complexity=5
    ),
    create_idea(
        id="assignment_help",
        title="Assignment Help Without Plagiarism for Students",
        problem="Indian college students copy-paste ChatGPT for assignments. Professors use Turnitin, catching plagiarism. Students fail/get warnings. Need help understanding concepts, structuring answers without direct copying.",
        target="College students (Tier-2/3), online course learners. Decision maker: Student.",
        ai="Explain concept (Socratic method, don't give direct answer). Suggest structure / outline for assignment. Paraphrase tool (rewrite in own words). Anti-plagiarism check (before submission). Citations generator.",
        mvp=["Web app: paste assignment question", "AI explains concept (step-by-step)", "Provides outline (not full answer)", "Paraphrase tool", "Check plagiarism score (before Turnitin)"],
        tech=["GPT-4o-mini (with careful prompting to not solve directly)", "FastAPI backend", "Next.js frontend", "Plagiarism check (Copyleaks API or build simple one)"],
        moat="Educational prompting (not cheating-focused). University-specific assignment patterns. Reputation.",
        pricing="Freemium: 5 queries/month. Pro: ₹299/month. Semester pass: ₹999 (4 months).",
        gtm=["Reddit (r/Indian_Academia)", "College WhatsApp groups", "Instagram meme pages (student-focused)", "Referral program (get friends to join)", "Content: 'How to use AI without plagiarism'"],
        risks=["Ethical concerns (still helping cheat?)", "ChatGPT free tier is 'good enough'", "Students won't pay", "Universities might ban AI tools entirely"],
        advantage="You understand the line between help vs cheating. You can build ethical guidelines. Student community trust.",
        domain_id="education", pain=7, weeks=2, market=8, complexity=4
    ),
    create_idea(
        id="coding_tutor_regional",
        title="Coding Tutor for Regional Language Students",
        problem="Tier-3 Indian students learning to code struggle with English. YouTube tutorials too fast. Can't ask questions. No one explains 'loop' in Telugu/Hindi. Drop out from coding courses.",
        target="Tier-3 college students, rural students learning online. Decision maker: Student (parent pays).",
        ai="Code explanation in regional language (Telugu, Hindi, Tamil). Interactive exercises (with hints in local language). Debug help (explain error in simple terms). Voice-based Q&A.",
        mvp=["Web app: paste code", "Get explanation in Telugu/Hindi", "Interactive exercises (basic Python)", "Chat for doubts (text-based)", "Progress tracking"],
        tech=["GPT-4o-mini (prompted for Telugu/Hindi output)", "FastAPI backend", "Next.js frontend", "Code execution sandbox (Piston API)"],
        moat="Regional language quality. Curriculum tailored to Indian universities. Community support.",
        pricing="Freemium: 10 explanations/month. Pro: ₹199/month. College partnership: bulk licenses.",
        gtm=["WhatsApp groups (regional language coding communities)", "YouTube tutorials in Telugu/Hindi (link to tool)", "College partnerships (Tier-3 engineering colleges)", "Free for first 100 students (testimonials)", "Parent outreach (local newspaper ads)"],
        risks=["Translation quality (technical terms in Telugu?)", "Will students actually pay?", "Low internet penetration in target segment", "Sustainability (VC-unfriendly market)"],
        advantage="Native speaker (Telugu). Deep empathy. You can create curriculum. Community building (not just tech).",
        domain_id="education", pain=9, weeks=3, market=6, complexity=5
    ),
    create_idea(
        id="worksheet_generator",
        title="Worksheet Generator for Indian Teachers",
        problem="Indian school teachers (CBSE, ICSE, State boards) create worksheets manually. Typing 20 math problems = 1 hour. Need variety (so students can't share answers). Exam season = 50 worksheets per teacher.",
        target="School teachers (Class 6-12), tuition centers, coaching institutes. Decision maker: Teacher / Tuition Owner.",
        ai="Generate practice problems (math, science, grammar). Parameterized questions (same type, different numbers). Difficulty levels. Solution sheets auto-generated. CBSE/ICSE syllabus-aligned.",
        mvp=["Web app: select subject, chapter, difficulty", "Generate 10-50 questions", "Export as PDF (formatted, printable)", "Answer key included", "Version control (generate multiple sets)"],
        tech=["GPT-4o-mini for question generation", "Template-based formatting", "Python (ReportLab for PDF)", "FastAPI backend", "Next.js frontend"],
        moat="Syllabus alignment (CBSE chapter-wise). Question quality. Template library.",
        pricing="Freemium: 5 worksheets/month. Pro: ₹499/month (unlimited). Tuition center: ₹2999/month (10 teachers).",
        gtm=["Facebook groups (teacher communities)", "WhatsApp groups (school teacher groups)", "Cold call to tuition centers", "Education conferences (CBSE seminars)", "Free for first 50 teachers (testimonials)"],
        risks=["Teachers share accounts (piracy)", "Free resources on internet (Teachoo, Khan Academy)", "Low willingness to pay (teacher salary constraints)", "Quality control (wrong answers = reputation damage)"],
        advantage="You can manually curate initial question bank. You can add Telugu/Hindi medium support. Iterative improvement with teacher feedback.",
        domain_id="education", pain=8, weeks=3, market=7, complexity=4
    ),
    create_idea(
        id="vocational_skills_assessment",
        title="Vocational Skills Assessment for Blue-Collar Workers",
        problem="Indian blue-collar workers (plumbers, electricians, beauticians) lack skill certifications. Employers can't verify skills. Workers lose job opportunities. Skill India certifications are bureaucratic (3-6 months).",
        target="B2C: workers seeking jobs. B2B: hiring platforms (UrbanClap, Quikr), employers (factories, construction).",
        ai="Video-based skill assessment (record task performance). AI evaluates (correctness, safety, speed). Issue digital certificate. Skill gap analysis + learning recommendations.",
        mvp=["Mobile app (video recording)", "3-5 skill tasks per trade (e.g., wire a socket)", "AI evaluation (simple rules + GPT-4o vision)", "Certificate generation (PDF)", "Profile page (shareable link)"],
        tech=["React Native app", "GPT-4o vision for video evaluation", "Simple rule-based checks", "Supabase for data", "PDF certificate generation"],
        moat="Employer network effects. Skill task library. Trust/brand.",
        pricing="B2C: ₹99 per assessment. B2B: ₹50/worker assessed (bulk). Platform partnerships: rev share.",
        gtm=["Partner with UrbanClap, Quikr", "WhatsApp outreach to worker groups", "Skill India centers (partnerships)", "Employer outreach (construction companies)", "Gig platform integrations"],
        risks=["Workers don't have smartphones (but improving)", "AI evaluation accuracy (safety-critical tasks)", "Trust ('Will employers accept this?')", "Government certification still preferred"],
        advantage="You can build trust through partnerships. You can do in-person assessments initially (hybrid). Iterative improvement with employer feedback.",
        domain_id="education", pain=8, weeks=4, market=6, complexity=6
    ),
    # --- DOMAIN 6: Finance / Accounting / Compliance ---
    create_idea(
        id="gst_return_filer",
        title="GST Return Auto-Filer for Small Businesses",
        problem="Indian SMBs (₹20L-₹5Cr turnover) file GST returns manually or pay CA ₹2k-₹5k/month. Data entry errors. Late filing penalties (₹200/day). GSTR-1, GSTR-3B confusion.",
        target="Small retailers, distributors, service businesses. 1-10 employees. Decision maker: Owner / Accountant.",
        ai="Auto-extract data from invoices (uploaded or scraped from email). Reconcile with purchase data. Pre-fill GST returns (GSTR-1, GSTR-3B). Error detection (missing GSTIN, mismatched amounts). One-click file to GSTN portal.",
        mvp=["Upload invoices (PDF, Excel, email forwarding)", "AI extracts GST data", "Dashboard: sales, purchases, tax liability", "Generate return JSONs (GSTR-1, GSTR-3B)", "Export or API push to GSTN (if API access)"],
        tech=["Donut for invoice OCR", "GPT-4o-mini for ambiguous field extraction", "GST reconciliation logic (Python)", "FastAPI backend", "Next.js frontend"],
        moat="Indian invoice format training. Integration with Tally/Zoho Books. Historical data for error prediction.",
        pricing="₹999/month (up to ₹1Cr turnover). ₹2999/month (₹1-5Cr). Annual: 20% discount.",
        gtm=["Google Ads (keyword: 'GST filing help')", "Cold call to businesses (from GST portal public data)", "Partner with CAs (white-label for their clients)", "Facebook groups (SMB owner communities)", "Free trial: file one return free"],
        risks=["ClearTax, Zoho Books exist (but clunky)", "Requires high accuracy (errors = penalties)", "GSTN API access restricted", "SMBs resist change ('CA knows my business')"],
        advantage="India-specific edge cases (composition scheme, reverse charge). You can offer hybrid (AI + human review). Fast iteration on error patterns.",
        domain_id="fintech", pain=9, weeks=4, market=8, complexity=7
    ),
    create_idea(
        id="expense_categorization",
        title="Expense Categorization for Freelancers & Consultants",
        problem="Indian freelancers, consultants track expenses in spreadsheets or not at all. Tax time = panic (reconstruct 12 months from bank statements). Miss deductions. Overpay tax. ITR filing nightmare.",
        target="Freelancers (designers, developers, writers), consultants, CA/lawyer practices. Decision maker: Self.",
        ai="Auto-categorize expenses from bank statements (rent, travel, software, meals). Receipt matching (link transaction to receipt photo). Tax deduction suggestions (which expenses are deductible). ITR pre-fill (income, deductions).",
        mvp=["Upload bank statement (PDF, CSV)", "AI categorizes transactions", "Add receipts (photo)", "Dashboard: monthly spend by category", "ITR export (summary for CA)"],
        tech=["PDF parsing (Tabula/Camelot)", "GPT-4o-mini for transaction categorization", "OCR for receipts (Donut)", "FastAPI backend", "Next.js frontend"],
        moat="Indian expense patterns. ITR integration. Historical data for anomaly detection.",
        pricing="Freemium: 50 transactions/month. Pro: ₹299/month. CA partner plan: ₹2999/month (50 clients).",
        gtm=["Reddit (r/IndiaInvestments, r/FIREIndia)", "LinkedIn posts targeting freelancers", "Partner with CA firms", "Content: 'Freelancer tax guide'", "Referral program"],
        risks=["Mint, Walnut exist (but no tax focus)", "Low willingness to pay (freelancers budget-conscious)", "Bank integration friction (no direct API access)", "Privacy concerns (bank statement data)"],
        advantage="You know freelancer pain. You can build for specific niches (developers, designers). Community-driven (Discord for tax help).",
        domain_id="fintech", pain=7, weeks=2, market=6, complexity=5
    ),
    create_idea(
        id="automated_bookkeeping",
        title="Automated Bookkeeping for Micro-Businesses",
        problem="Indian micro-businesses (salons, tutors, small shops) don't maintain books. Cash transactions, no invoices. Tax notice = scramble to reconstruct. Lose deductions. Overpay or underpay tax.",
        target="Micro-businesses (₹5L-₹50L revenue). 1-3 employees. Decision maker: Owner.",
        ai="WhatsApp bot: 'Send photo of bill'. Extract: date, amount, party, category. Maintain ledger (income, expense). Monthly P&L summary. Tax estimate.",
        mvp=["WhatsApp bot", "Photo → extract data", "Simple ledger (income/expense)", "Monthly summary (PDF via WhatsApp)", "Tax liability estimate"],
        tech=["WhatsApp Business API", "Donut/TrOCR for receipt OCR", "GPT-4o-mini for categorization", "Postgres on Supabase", "Python backend on Railway"],
        moat="Simplicity (WhatsApp-only). Indian receipt formats. Local language support.",
        pricing="₹199/month. Or ₹10/transaction (pay-as-you-go). Annual: ₹1999.",
        gtm=["Walk into salons, tuition centers", "WhatsApp business groups", "Local newspaper ads (Tier-2 cities)", "Referral program (₹100 per referral)", "Free for 2 months"],
        risks=["Digital literacy (can they use WhatsApp bot?)", "Willingness to pay (₹199 = 1 day revenue)", "Cash economy (no digital records)", "GST threshold (many are below ₹20L, don't need this)"],
        advantage="You can do in-person onboarding. Local language support (Telugu). Hyper-local (one neighborhood at a time). Community trust.",
        domain_id="fintech", pain=8, weeks=3, market=9, complexity=6
    ),
    create_idea(
        id="invoice_financing_calc",
        title="Invoice Financing Eligibility Checker",
        problem="Indian SMBs have unpaid invoices (₹5L-₹50L). Need working capital but banks reject. Invoice discounting platforms (KredX, InvoiceMart) exist but SMBs don't know eligibility. Application = 2-3 days → rejection.",
        target="SMBs with B2B clients. ₹1-20Cr revenue. Decision maker: Owner / CFO.",
        ai="Analyze invoice data (client creditworthiness, payment history). Predict financing eligibility (which invoices will be accepted). Compare platforms (KredX vs Falcon vs traditional bank). Application pre-fill.",
        mvp=["Upload invoices", "AI scores each invoice (financing likelihood)", "Recommend best platform", "Generate application summary", "Link to platforms"],
        tech=["PDF parsing", "Simple ML model (or rule-based scoring)", "GPT-4o-mini for client name normalization", "FastAPI backend", "Next.js frontend"],
        moat="Historical acceptance data (from platforms). Client creditworthiness database. Platform partnerships.",
        pricing="Free (rev share from platforms on successful financing). Or ₹999 per eligibility check.",
        gtm=["Partner with invoice financing platforms", "Cold email to SMBs (from business directories)", "LinkedIn outreach to CFOs", "Content: 'Invoice financing guide for SMBs'", "CA partnerships (they refer clients)"],
        risks=["Platforms won't share data (competitive threat)", "Low transaction volume (finance 2-3x/year)", "Accuracy needs to be high (false hope = angry customers)", "Market education needed (many don't know invoice financing exists)"],
        advantage="You can build relationships with platforms. You can offer consulting alongside tool. Niche focus (high intent users).",
        domain_id="fintech", pain=7, weeks=3, market=7, complexity=6
    ),
    create_idea(
        id="compliance_calendar",
        title="Compliance Calendar & Reminder for Indian Businesses",
        problem="Indian businesses miss compliance deadlines: TDS filing, GST returns, PF/ESI, ROC filings, labor law compliance. Penalties = ₹10k-₹5L. CA sends reminders but businesses forget.",
        target="SMBs, startups (10-200 employees). Decision maker: Founder / CFO / Compliance Head.",
        ai="Personalized compliance calendar (based on business type, state, employee count). Smart reminders (email, WhatsApp, Slack). Document checklist (what to prepare). Penalty calculator (cost of missing). Integration with CA (share calendar).",
        mvp=["Onboarding: business type, state, employee count", "Generate compliance calendar (12 months)", "Reminder system (7 days, 3 days, 1 day before)", "Dashboard: upcoming, completed, missed", "Export/share with CA"],
        tech=["Rule-based calendar generation (compliance data scraped)", "FastAPI backend", "Next.js frontend", "Reminder system (cron jobs + email/WhatsApp)", "Postgres on Supabase"],
        moat="Comprehensive compliance database. State-specific variations. CA network.",
        pricing="₹999/month per business. CA partner plan: ₹4999/month (20 clients). Annual: 25% discount.",
        gtm=["Cold email to startups (YourStory database)", "Partner with CA firms (white-label)", "LinkedIn outreach to CFOs", "Content: 'Indian startup compliance checklist'", "Free for first 3 months (case studies)"],
        risks=["Calendars already exist (free from CA associations)", "Requires continuous updates (govt rule changes)", "Low perceived value ('I have a CA for this')", "CAs might resist (reduces their value)"],
        advantage="You can maintain compliance database religiously. You can add state-specific nuances (Telangana shops & establishments act). Rapid updates on regulatory changes.",
        domain_id="fintech", pain=8, weeks=3, market=7, complexity=5
    ),

    # --- DOMAIN 7: Legal / Contracts ---
    create_idea(
        id="rent_agreement",
        title="Rent Agreement Generator for Indian Landlords",
        problem="Indian landlords create rent agreements manually (templates from Google, errors). Stamp paper confusion (state-specific). Missing clauses (lock-in, notice period). Disputes later. Lawyer = ₹5k-₹10k.",
        target="Individual landlords, property dealers, rental platforms. Decision maker: Landlord / Property Manager.",
        ai="Questionnaire (property details, terms). Generate customized agreement (state-specific clauses). Stamp paper calculation (state-wise). E-sign integration. Reminder: rent due, agreement renewal.",
        mvp=["Web form: property, tenant, rent, deposit, duration", "Generate agreement (PDF, editable)", "State-specific clauses (Maharashtra vs Karnataka)", "E-stamp integration (if API available)", "Export for printing"],
        tech=["Template engine (Jinja2)", "GPT-4o-mini for clause customization", "FastAPI backend", "Next.js frontend", "E-sign via DigiLocker API (if accessible)"],
        moat="State-specific legal accuracy. Integration with rental platforms (NoBroker, Housing.com). Trust/brand.",
        pricing="₹299 per agreement. Subscription: ₹999/month (5 agreements). Property dealer: ₹4999/month (unlimited).",
        gtm=["Google Ads (keyword: 'rent agreement online')", "Partner with NoBroker, Housing.com", "Facebook groups (landlord communities)", "Local property dealer outreach", "Content: 'Rent agreement clauses to include'"],
        risks=["LegalDesk, LawRato exist (competitors)", "Free templates available online", "Stamp paper ecosystem complex (offline dependency)", "Legal liability ('Agreement was invalid, I'm sued')"],
        advantage="State-specific depth (Telangana, Karnataka). You can offer lawyer review (hybrid). Fast iteration on edge cases.",
        domain_id="legal", pain=7, weeks=2, market=7, complexity=5
    ),
    create_idea(
        id="nda_generator",
        title="NDA Generator & Tracker for Startups",
        problem="Indian startups sign 20-50 NDAs/year (investors, vendors, partners). Manual drafting = 2-3 hours per NDA. Track expiry? Forget it. Violation? No record of who signed what.",
        target="Startups (seed to Series A), agencies. Decision maker: Founder / Legal/Ops head.",
        ai="NDA template library (mutual, unilateral, vendor, investor). Customization (company names, duration, jurisdiction). E-sign integration. Tracker: who signed, expiry date, status. Reminder: renewal/expiry.",
        mvp=["Web app: select NDA type", "Fill details (parties, confidentiality period, jurisdiction)", "Generate PDF", "E-sign (DigiSign/DocuSign integration)", "Dashboard: signed NDAs, expiring soon"],
        tech=["Template engine", "GPT-4o-mini for customization", "FastAPI backend", "Next.js frontend", "DigiSign API (₹10-₹20 per signature)"],
        moat="Indian jurisdiction templates. Integration with CRM/deal flow tools. Network effects (both parties use same tool).",
        pricing="Freemium: 3 NDAs/month. Pro: ₹999/month (unlimited). Enterprise: ₹4999/month + API access.",
        gtm=["LinkedIn outreach to founders", "Post in founder Slack groups", "Partner with accelerators (YC, Antler)", "Content: 'NDA mistakes startups make'", "ProductHunt launch"],
        risks=["DocuSign, Adobe Sign exist (but expensive, complex)", "Law firms offer free NDAs (to get business)", "Low frequency (sign 20-50/year, not daily)", "Enforceability concerns ('Is this legally sound?')"],
        advantage="India-specific (jurisdiction, stamp paper). Startup-friendly pricing. You know founder pain. Rapid iteration.",
        domain_id="legal", pain=6, weeks=2, market=6, complexity=4
    ),
    create_idea(
        id="legal_notice_response",
        title="Legal Notice Response Generator",
        problem="Indian SMBs receive legal notices (customer disputes, vendor issues, employee). Panic. Lawyer consult = ₹10k-₹50k. Timeline pressure (7-15 days to respond). Many ignore → default judgment.",
        target="SMBs, startups, individuals. Decision maker: Owner / Founder.",
        ai="Upload legal notice (PDF). AI extracts: claims, timeline, sender. Generate response draft (point-by-point rebuttal). Suggest next steps (settle, fight, ignore). Lawyer matching (if needed).",
        mvp=["Upload notice PDF", "AI extracts key points", "Generate response template (editable)", "Risk assessment (likelihood of litigation)", "Export for lawyer review"],
        tech=["PDF parsing (PyMuPDF)", "GPT-4o for analysis + draft generation", "LangChain for structured extraction", "FastAPI backend", "Next.js frontend"],
        moat="Indian legal terminology. Case law database (if built). Lawyer network.",
        pricing="₹1999 per notice analysis. Or ₹9999/month (5 notices). Lawyer referral: rev share.",
        gtm=["Google Ads (keyword: 'legal notice received')", "Partner with law firms (lead generation)", "LinkedIn outreach to founders", "Content: 'How to respond to legal notice'", "Quora answers (legal help queries)"],
        risks=["Liability ('AI advice was wrong, I lost case')", "Requires lawyer review anyway (limited value)", "Low volume (receive notice 1-2x in lifetime)", "People prefer human lawyer (trust)"],
        advantage="You can offer free initial analysis (lead gen for lawyers). You can focus on specific notice types (copyright, defamation). Rapid iteration on templates.",
        domain_id="legal", pain=9, weeks=3, market=5, complexity=7
    ),
    create_idea(
        id="freelance_contract_market",
        title="Freelance Contract Template Marketplace",
        problem="Indian freelancers (designers, developers, writers) use no contracts or generic templates. Scope creep, payment disputes. Client: 'I never agreed to that'. Lawyer = ₹5k-₹20k per contract.",
        target="Freelancers, agencies (5-20 people). Decision maker: Freelancer / Agency Owner.",
        ai="Contract template library (by industry: dev, design, content). AI customization (project-specific clauses). E-sign integration. Milestone tracking (link to invoicing). Dispute resolution guidance.",
        mvp=["Template marketplace (10-20 contracts)", "Customization wizard (Q&A → personalized contract)", "Preview + export (PDF, Word)", "E-sign (DigiSign integration)", "Payment milestone tracker"],
        tech=["Template library (legal-reviewed)", "GPT-4o-mini for customization", "FastAPI backend", "Next.js frontend", "DigiSign API"],
        moat="Template quality (lawyer-reviewed). Industry-specific (UX/UI design contract vs backend dev). Community trust.",
        pricing="Pay-per-contract: ₹499. Subscription: ₹999/month (5 contracts). Agency: ₹4999/month (unlimited).",
        gtm=["LinkedIn outreach to freelancers", "Post in freelance communities (Upwork India, Fiverr forums)", "Partner with freelance platforms", "Content: 'Contract clauses to protect yourself'", "Free template (limited features) for lead gen"],
        risks=["Free templates available (limited customization)", "Freelancers won't pay (budget-conscious)", "Clients resist signing ('Why now? We've worked before')", "Enforcement (small disputes, not worth legal fight)"],
        advantage="You know freelancer pain. You can build community (not just contracts). India-specific (payment terms, IP clauses). Rapid iteration.",
        domain_id="legal", pain=7, weeks=2, market=6, complexity=4
    ),
    create_idea(
        id="poa_fraud_detection",
        title="Power of Attorney Fraud Detection",
        problem="Indian property deals, elderly care involve PoAs. Fraud common (forged signatures, coerced PoAs, expired PoAs). Banks, property registrars need to verify. Manual verification = unreliable.",
        target="B2B: Banks, property registrars, law firms. B2C: Individuals verifying PoAs.",
        ai="Document verification (PoA format, stamps, signatures). Signature comparison (forensic-grade). Cross-check with govt databases (if accessible). Red flag detection (unusual clauses, expired dates).",
        mvp=["Upload PoA (PDF/image)", "AI checks: format validity, stamp paper authenticity, signature consistency", "Risk score (low/medium/high)", "Report generation (for submission)"],
        tech=["Computer vision (signature analysis)", "GPT-4o vision for document analysis", "Rule-based checks (date, format)", "FastAPI backend", "Next.js frontend"],
        moat="Forensic database (signature patterns). Government partnerships. High-stakes use case.",
        pricing="B2B: ₹50-₹200 per verification. Enterprise: ₹49,999/month (unlimited). B2C: ₹499 per verification.",
        gtm=["Direct sales to banks (Axis, ICICI)", "Property registrar office pilots", "Law firm partnerships", "Content: 'PoA fraud cases in India'", "Government tenders (if possible)"],
        risks=["Requires extremely high accuracy (false negative = fraud goes through)", "Regulatory approval needed (govt agencies)", "Liability (missed fraud = sued)", "Limited market (not daily use case)"],
        advantage="You can build trust through partnerships (banks, govt). You can offer hybrid (AI + human forensic expert). Niche focus (less competition).",
        domain_id="legal", pain=8, weeks=4, market=6, complexity=8
    ),
    # --- DOMAIN 8: Sales / Marketing / Growth ---
    create_idea(
        id="cold_email_personalization",
        title="Cold Email Personalization at Scale for B2B",
        problem="Indian B2B founders, agencies send generic cold emails. Open rate <5%, reply rate <0.5%. Hiring SDRs = ₹30k-₹50k/month. Tools like Lemlist expensive. Need personalization: reference company, recent news, pain points.",
        target="B2B SaaS founders, agencies, sales teams. 1-50 employees. Decision maker: Founder / Sales Lead.",
        ai="Scrape prospect info (LinkedIn, company website, news). Generate personalized email (GPT-4o-mini). A/B test subject lines. Follow-up sequence generation. Deliverability monitoring.",
        mvp=["Upload prospect list (CSV: name, company, LinkedIn)", "AI generates personalized emails", "Preview + edit", "Send via SMTP (Gmail, Outlook)", "Track: open, reply rates"],
        tech=["Web scraping (Playwright/Selenium)", "GPT-4o-mini for email generation", "SMTP integration", "FastAPI backend", "Next.js frontend"],
        moat="Personalization quality. Indian company data (scraped from local sources). Deliverability expertise.",
        pricing="₹4999/month for 500 emails. ₹9999/month for 2000 emails. Enterprise: ₹29,999/month + white-label.",
        gtm=["Use the tool on yourself (meta)", "LinkedIn outreach to B2B founders", "Post in sales/growth communities", "Cold email to dev agencies", "Case study: '50% open rate with personalization'"],
        risks=["Lemlist, Instantly, Smartlead exist (competitors)", "Email deliverability hard (spam filters)", "Scraping = legal gray area (LinkedIn ToS)", "Personalization quality (generic = worse than no tool)"],
        advantage="India-specific data sources. Founder-to-founder empathy. You can offer managed service (hybrid). Rapid iteration on templates.",
        domain_id="sales_marketing", pain=8, weeks=3, market=8, complexity=6
    ),
    create_idea(
        id="competitor_monitor",
        title="Competitor Monitoring Dashboard for Indian Startups",
        problem="Indian startups track competitors manually (visit websites, check LinkedIn, Google Alerts). Miss product launches, pricing changes, hiring sprees, funding news. Competitive intelligence = scattered, ad hoc.",
        target="Startups (seed to Series B), product managers. Decision maker: Founder / Product Lead.",
        ai="Scrape competitor websites (product pages, pricing, blog). Monitor hiring (LinkedIn, AngelList). Track funding (Crunchbase, news). Summarize changes (weekly digest). Alert on major updates (pricing drop, new feature).",
        mvp=["Add 3-5 competitors (URLs)", "Daily scraping (website, blog, LinkedIn)", "Diff detection (changes highlighted)", "Weekly email digest", "Dashboard: timeline of competitor moves"],
        tech=["Web scraping (Playwright)", "Diff detection (simple text comparison)", "GPT-4o-mini for summarization", "Cron jobs for scheduling", "FastAPI backend, Next.js frontend"],
        moat="Data quality. Indian startup focus. Integration with Slack, Notion.",
        pricing="₹4999/month for 5 competitors. ₹9999/month for 15 competitors. Enterprise: ₹29,999/month + API access.",
        gtm=["LinkedIn outreach to founders, PMs", "Post in product management groups", "ProductHunt launch", "Content: 'How to track competitors'", "Free trial: 1 competitor, 1 week"],
        risks=["Scraping = brittle (websites change)", "Legal concerns (scraping ToS violations)", "Signal vs noise (too many alerts = ignored)", "Competitors block scraping (Cloudflare)"],
        advantage="You know startup pain. You can curate Indian startup data (YourStory, Inc42). Rapid iteration on alert logic.",
        domain_id="sales_marketing", pain=7, weeks=3, market=7, complexity=5
    ),
    create_idea(
        id="seo_brief_gen",
        title="SEO Content Brief Generator for Agencies",
        problem="Indian content agencies, SEO teams create content briefs manually. Keyword research (Ahrefs, SEMrush = expensive). Analyze top 10 results, extract structure, outline. 2-4 hours per brief. Writers wait, idle time.",
        target="Content agencies (10-50 people), in-house SEO teams. Decision maker: Content Lead / SEO Manager.",
        ai="Keyword research (scrape Google Suggest, Related Searches). Scrape top 10 results (extract: H2/H3 structure, word count, topics covered). Generate brief (outline, target keywords, word count, FAQs). Competitor gap analysis (topics they cover, you don't).",
        mvp=["Input: target keyword", "AI generates: outline, word count, FAQs, related keywords", "Export as PDF/Word", "Brief library (search past briefs)"],
        tech=["Web scraping (SERP analysis)", "GPT-4o-mini for outline generation", "FastAPI backend", "Next.js frontend", "Export to Notion, Google Docs"],
        moat="Brief quality. Integration with content management tools (ContentStudio, CoSchedule). Template customization.",
        pricing="₹4999/month for 50 briefs. ₹9999/month for 200 briefs. Agency: ₹29,999/month unlimited.",
        gtm=["Cold email to content agencies", "LinkedIn outreach to SEO Managers", "Post in SEO communities (r/SEO, SEO Discord)", "Partner with Ahrefs, SEMrush (app marketplace)", "Free trial: 5 briefs"],
        risks=["Clearscope, Surfer SEO exist (but expensive)", "Google search = free (manual but works)", "Quality concerns (briefs need human touch)", "SERP scraping = legal gray area"],
        advantage="India pricing (10x cheaper than Clearscope). Indian SERP nuances. Fast iteration on brief templates. Agency partnerships.",
        domain_id="sales_marketing", pain=8, weeks=3, market=7, complexity=6
    ),
    create_idea(
        id="whatsapp_campaign_manager",
        title="WhatsApp Broadcast Campaign Manager",
        problem="Indian SMBs, D2C brands use WhatsApp Business for marketing. Manual broadcast (1000 messages = 2-3 hours). No analytics (who opened, clicked). No segmentation. Contacts = Excel chaos.",
        target="D2C brands, local businesses, influencers. 1-20 employees. Decision maker: Owner / Marketing Manager.",
        ai="Contact list management (import, deduplication). Segmentation (by purchase history, engagement). Message template generation (GPT-4o-mini). Scheduled broadcasts. Analytics (delivered, read, clicked).",
        mvp=["Web dashboard", "Import contacts (CSV, Excel)", "Create broadcast campaign", "Message templates + personalization (name, etc.)", "Schedule send", "Track delivery, read status"],
        tech=["WhatsApp Business API (₹500-₹2000/month)", "FastAPI backend", "React dashboard", "Postgres on Supabase", "Analytics (simple metrics)"],
        moat="Template library. Indian small business workflows. Integration with Shopify, WooCommerce.",
        pricing="₹2999/month for 5000 messages. ₹6999/month for 20k messages. Enterprise: custom pricing.",
        gtm=["Instagram DM to D2C brands", "Cold call to businesses (WhatsApp-heavy industries)", "Partner with e-commerce platforms", "Content: 'WhatsApp marketing guide'", "Free trial: 500 messages"],
        risks=["WATI, Interakt exist (competitors)", "WhatsApp policy changes (crackdown on spam)", "Spam reputation (people hate unsolicited messages)", "Low differentiation (similar to existing tools)"],
        advantage="India-specific (regional language templates). SMB-friendly pricing. You can offer message consulting. Rapid iteration.",
        domain_id="sales_marketing", pain=8, weeks=3, market=8, complexity=5
    ),
    create_idea(
        id="landing_page_ab_analyzer",
        title="Landing Page A/B Test Analyzer",
        problem="Indian startups, agencies run A/B tests (Optimizely, VWO = expensive). Results: 'Variant B won 52% vs 48%'. Now what? No insights on _why_. No next test suggestions. Analysis = 2-3 hours per test.",
        target="Startups (growth teams), agencies. 5-50 employees. Decision maker: Growth Lead / Founder.",
        ai="Connect to analytics (Google Analytics, Mixpanel). Analyze test results (statistical significance, segment analysis). GPT-4o generates insights ('B won because mobile users preferred shorter form'). Suggest next tests (what to test next). Report generation.",
        mvp=["Connect Google Analytics", "Upload test data (variant A, B, metrics)", "AI analysis: significance, segment breakdown", "Insight generation (plain English)", "Next test suggestions"],
        tech=["Google Analytics API", "GPT-4o-mini for insight generation", "Statistical analysis (Python scipy)", "FastAPI backend", "Next.js frontend"],
        moat="Insight quality. Integration with testing tools. Learning from past tests.",
        pricing="₹4999/month for 10 analyses. ₹9999/month unlimited. Enterprise: ₹29,999/month + custom reports.",
        gtm=["LinkedIn outreach to growth PMs", "Post in growth marketing communities", "Partner with VWO, Optimizely", "Content: 'A/B testing mistakes'", "Free analysis of 1 test"],
        risks=["VWO, Optimizely have built-in analytics (but basic)", "Requires understanding of statistics (target audience sophisticated)", "Low frequency (run 5-20 tests/year)", "Insight quality variable (sometimes no clear answer)"],
        advantage="You know growth experimentation. You can offer consulting alongside. India-specific (mobile-first, price-sensitive users). Rapid iteration on insight generation.",
        domain_id="sales_marketing", pain=7, weeks=3, market=6, complexity=6
    ),

    # --- DOMAIN 9: HR / Hiring ---
    create_idea(
        id="resume_screening",
        title="Resume Screening & Shortlisting for Indian Recruiters",
        problem="Indian HR teams, recruiters screen 100-500 resumes per job posting. 80% clearly unqualified. Manual screening = 3-5 hours. Miss qualified candidates (buried in pile). ATS systems clunky (Naukri, LinkedIn Recruiter expensive).",
        target="Startups, SMBs (hiring 2-20 people/year), recruitment agencies. Decision maker: HR Lead / Founder.",
        ai="Parse resumes (extract: skills, experience, education). Match to job description. Score candidates (1-100). Red flags (job hopping, employment gaps). Auto-generate shortlist + rejection emails.",
        mvp=["Upload job description", "Upload resumes (PDF, bulk)", "AI scores each resume", "Shortlist view (top 10-20%)", "Export to CSV, send to hiring manager"],
        tech=["Resume parsing (PyMuPDF + GPT-4o-mini)", "Matching algorithm (simple semantic similarity)", "FastAPI backend", "Next.js frontend", "Email integration (rejection emails)"],
        moat="Indian resume format training. Integration with Naukri, LinkedIn. Historical hiring data (what profiles succeeded).",
        pricing="₹4999/month for 200 resumes. ₹9999/month for 1000 resumes. Agency: ₹29,999/month unlimited.",
        gtm=["Cold email to HR Leads (from LinkedIn)", "Partner with recruitment agencies", "Post in HR communities", "LinkedIn ads targeting 'Recruiter'", "Free trial: screen 50 resumes"],
        risks=["Greenhouse, Lever, Workable exist (but expensive, US-focused)", "Bias concerns (AI might discriminate)", "Resume parsing accuracy (Indian formats messy)", "Recruiters resist automation (job security)"],
        advantage="India-specific (IITs, NITs recognition). Affordable pricing. You can offer bias audits. Rapid iteration on edge cases.",
        domain_id="hr_hiring", pain=9, weeks=3, market=8, complexity=6
    ),
    create_idea(
        id="interview_scheduler",
        title="Interview Scheduling Assistant",
        problem="Indian HR teams coordinate interviews (candidate + 3-4 interviewers). Email ping-pong (10-15 emails per interview). Timezone confusion. Calendar conflicts. Rescheduling = another 10 emails. 30-60 min per interview scheduled.",
        target="Startups, SMBs (hiring 5-50 people/year). Decision maker: HR Lead / Ops Manager.",
        ai="Check interviewer calendars (Google Calendar integration). Suggest time slots. Send invite to candidate. Auto-reschedule if conflict. Reminder emails (day before, 1 hour before).",
        mvp=["Google Calendar integration", "Find common availability (candidate + interviewers)", "Send calendar invite", "Rescheduling flow", "Dashboard: upcoming interviews"],
        tech=["Google Calendar API", "FastAPI backend", "Next.js frontend", "Email automation", "Postgres on Supabase"],
        moat="Multi-interviewer coordination. Integration with ATS (Greenhouse, Lever). Indian timezone handling.",
        pricing="₹4999/month for 50 interviews. ₹9999/month for 200 interviews. Enterprise: ₹29,999/month unlimited.",
        gtm=["Cold email to HR Leads", "LinkedIn outreach", "Partner with ATS providers", "Post in HR communities", "Free trial: 10 interviews"],
        risks=["Calendly exists (but no multi-party optimization)", "Integration friction (need calendar access)", "Edge cases (last-minute changes, timezone confusion)", "Low perceived value (existing tools 'good enough')"],
        advantage="India-specific (IST timezone, local holidays). Multi-interviewer optimization. Rapid iteration on edge cases.",
        domain_id="hr_hiring", pain=7, weeks=3, market=7, complexity=5
    ),
    create_idea(
        id="onboarding_checklist",
        title="Employee Onboarding Checklist Automation",
        problem="Indian startups onboard 5-50 employees/year. HR tracks manually: offer letter, background verification, IT setup, training. Tasks slip through cracks. New hire Day 1 = laptop not ready. Bad first impression.",
        target="Startups, SMBs (20-200 employees). Decision maker: HR Lead / Ops Manager.",
        ai="Template onboarding checklist (by role, department). Task assignment (HR, IT, Manager). Reminder system (Slack, email). Progress tracking. Document collection (PAN, Aadhaar, certificates).",
        mvp=["Onboarding checklist template library", "Assign tasks to team members", "Reminder automation", "Dashboard: onboarding progress", "Integration with HRMS (Keka, GreytHR)"],
        tech=["FastAPI backend", "Next.js frontend", "Postgres on Supabase", "Slack/email integration", "Document storage (Supabase storage)"],
        moat="Indian compliance checklist (PF, ESI, labor laws). HRMS integrations. Workflow customization.",
        pricing="₹4999/month for 20 employees/year. ₹9999/month for 100 employees/year. Enterprise: custom pricing.",
        gtm=["Cold email to HR Leads", "Partner with HRMS providers", "LinkedIn outreach", "Post in HR communities", "Free for first 5 hires (case study)"],
        risks=["BambooHR, Workday have onboarding modules (but expensive, complex)", "Trello, Asana can replicate (low-tech solution)", "Low frequency (onboard 5-50/year, not daily)", "Requires process discipline (HR teams often ad hoc)"],
        advantage="India-specific compliance. Integration with Indian HRMS. You can offer onboarding consulting. Rapid iteration.",
        domain_id="hr_hiring", pain=7, weeks=3, market=7, complexity=5
    ),
    create_idea(
        id="pulse_survey_analyzer",
        title="Employee Feedback Pulse Survey Analyzer",
        problem="Indian startups run quarterly/annual employee surveys (Google Forms, SurveyMonkey). 200 responses = 50 pages of text. HR reads manually, takes 5-10 hours. Sentiment analysis = gut feel. No actionable insights.",
        target="Startups (50-500 employees). Decision maker: HR Lead / COO.",
        ai="Survey response ingestion (Google Forms, Typeform). Sentiment analysis (positive, negative, neutral). Theme extraction (compensation, culture, management, workload). Department/role segmentation. Actionable recommendations.",
        mvp=["Connect Google Forms / upload CSV", "AI analyzes: sentiment, themes", "Dashboard: overall sentiment, theme breakdown", "Segment view (engineering vs sales)", "Report generation (PDF for leadership)"],
        tech=["Google Forms API / CSV import", "GPT-4o-mini for theme extraction", "Sentiment analysis (simple classifier or GPT)", "FastAPI backend", "Next.js dashboard"],
        moat="Analysis quality. Integration with HRMS. Historical trend analysis (quarter-over-quarter).",
        pricing="₹9999 per survey analysis. Or ₹29,999/year (4 surveys). Enterprise: custom pricing.",
        gtm=["LinkedIn outreach to HR Leads, COOs", "Post in HR communities", "Partner with survey tools (SurveyMonkey, Typeform)", "Content: 'Employee feedback analysis guide'", "Free analysis of one past survey"],
        risks=["Qualtrics, Culture Amp exist (but expensive, US-focused)", "Low frequency (survey 1-4x/year)", "Requires large enough company (50+ employees for meaningful data)", "Trust concerns (will employees be honest if AI analyzes?)"],
        advantage="India pricing. Founder-to-founder empathy (you know the pain). You can offer action planning consulting. Rapid iteration on insights.",
        domain_id="hr_hiring", pain=7, weeks=3, market=6, complexity=5
    ),
    create_idea(
        id="reference_check",
        title="Automated Reference Check for Indian Hiring",
        problem="Indian companies do reference checks manually (call 2-3 references, 30 min/call). Candidate cherry-picks references (always positive). Fake references common. No standardized questions. Inconsistent signal.",
        target="Startups, SMBs, recruitment agencies. Decision maker: HR Lead / Founder.",
        ai="Automated reference check (email/phone survey). Standardized questions (performance, teamwork, rehire-ability). Sentiment analysis. Red flag detection (evasive answers, inconsistencies). Score + report generation.",
        mvp=["Candidate provides reference contacts", "Auto-send survey (email, WhatsApp)", "Collect responses", "AI analyzes: sentiment, consistency", "Generate reference check report"],
        tech=["Email/WhatsApp automation", "GPT-4o-mini for analysis", "FastAPI backend", "Next.js dashboard", "Report generation (PDF)"],
        moat="Question quality. Indian professional context. Fraud detection (fake references).",
        pricing="₹499 per reference check. Or ₹4999/month for 20 checks. Agency: ₹29,999/month unlimited.",
        gtm=["Cold email to HR Leads", "Partner with recruitment agencies", "LinkedIn outreach", "Post in HR communities", "Free for first 10 checks (case studies)"],
        risks=["Checkr, SkillSurvey exist (but US-focused)", "References might not respond (email fatigue)", "Fake references can game system (use friend's email)", "Trust concerns (candidates nervous about automated checks)"],
        advantage="India-specific (local professional norms). Affordable pricing. You can offer hybrid (AI + human calls for suspicious cases). Rapid iteration.",
        domain_id="hr_hiring", pain=8, weeks=3, market=7, complexity=5
    ),

    # --- DOMAIN 10: Customer Support ---
    create_idea(
        id="ticket_tagging",
        title="Support Ticket Auto-Tagging & Routing",
        problem="Indian SaaS companies, e-commerce get 100-500 support tickets/day. Agents manually read, categorize, route. 20-30% mis-routed (technical ticket to billing team). SLA breaches. Customer frustration.",
        target="SaaS companies, e-commerce, B2B service companies. 20-200 employees. Decision maker: Support Lead / COO.",
        ai="Ticket classification (billing, technical, feature request, bug). Priority scoring (angry customer, VIP, urgency keywords). Auto-routing to right team/agent. Suggested macros (common responses).",
        mvp=["Integration with Freshdesk, Zoho Desk, Zendesk", "Auto-tag incoming tickets", "Priority score (1-10)", "Routing rules (customizable)", "Dashboard: ticket volume by category"],
        tech=["Freshdesk/Zendesk API", "GPT-4o-mini for classification", "FastAPI backend", "Next.js dashboard", "Postgres for analytics"],
        moat="Company-specific training (learns your ticket patterns). Integration depth. Historical accuracy data.",
        pricing="₹4999/month for 1000 tickets. ₹9999/month for 5000 tickets. Enterprise: ₹29,999/month unlimited.",
        gtm=["Cold email to Support Leads", "Partner with Freshdesk, Zoho (app marketplace)", "LinkedIn outreach", "Case study: 'Reduced mis-routing by 60%'", "Free trial: 500 tickets"],
        risks=["Zendesk, Freshdesk have AI features (but basic)", "Requires high accuracy (mis-routing worse than manual)", "Integration friction (need API access)", "Support teams resist change"],
        advantage="You can customize for Indian customer language (Hinglish). You can offer setup consulting. Rapid iteration on edge cases.",
        domain_id="customer_support", pain=9, weeks=3, market=8, complexity=6
    ),
    create_idea(
        id="churn_prediction",
        title="Customer Churn Prediction for SaaS",
        problem="Indian SaaS companies lose 20-40% of customers annually. Churn = silent (no warning). Realize when renewal doesn't happen. Could have saved with intervention (discount, support call). No data-driven early warning.",
        target="B2B SaaS companies (₹5L-₹10Cr ARR). Decision maker: Founder / Customer Success Lead.",
        ai="Analyze usage data (login frequency, feature usage, support tickets). Churn prediction model (30/60/90 day risk score). Early warning alerts. Intervention suggestions (offer discount, assign CS rep, feature training).",
        mvp=["Connect to product analytics (Mixpanel, Amplitude) or DB", "Churn risk dashboard (list of at-risk customers)", "Risk score per customer (1-100)", "Suggested interventions", "Historical accuracy tracking"],
        tech=["Mixpanel/Amplitude API or direct DB connection", "Scikit-learn for churn model (logistic regression, random forest)", "FastAPI backend", "Next.js dashboard", "Postgres for storage"],
        moat="Model accuracy improves with data. Company-specific churn signals. Integration with CRM (HubSpot, Pipedrive).",
        pricing="₹9999/month for <500 customers. ₹29,999/month for 500-2000 customers. Enterprise: custom pricing.",
        gtm=["LinkedIn outreach to SaaS founders, CS leads", "Post in SaaS founder communities", "Partner with analytics tools", "Content: 'SaaS churn prevention guide'", "Free churn audit (analyze past 6 months)"],
        risks=["ChurnZero, Gainsight exist (but expensive, US-focused)", "Requires enough historical data (100+ churns)", "Model accuracy variable (sometimes unpredictable churn)", "Interventions don't always work (customer committed to leaving)"],
        advantage="India pricing. Founder-to-founder empathy. You can offer CS consulting alongside. Rapid iteration on models.",
        domain_id="customer_support", pain=9, weeks=3, market=6, complexity=7
    ),
    create_idea(
        id="ecommerce_chatbot",
        title="Support Chatbot for Indian E-commerce",
        problem="Indian e-commerce (D2C brands, marketplaces) get repetitive queries: 'Where is my order?', 'How to return?', 'Size chart?'. 60-70% are FAQ-answerable. Support agents waste time. Chat abandonment = lost sales.",
        target="D2C brands, small e-commerce, marketplace sellers. Decision maker: Owner / Support Lead.",
        ai="RAG over: FAQs, return policy, size charts, order data. Answer customer queries (chat on website). Escalate to human (complex issues). Order tracking integration (Shiprocket, Delhivery).",
        mvp=["Website chat widget", "Train on: FAQ docs, policies", "Answer common queries", "Order tracking (enter order ID)", "Escalation to human (button)"],
        tech=["LangChain for RAG", "GPT-4o-mini", "Pinecone/Qdrant free tier", "FastAPI backend", "React chat widget"],
        moat="Indian e-commerce workflows (COD, returns). Integration with Shopify, WooCommerce, Shiprocket. Regional language support.",
        pricing="₹2999/month for 1000 conversations. ₹6999/month for 5000 conversations. Enterprise: ₹19,999/month unlimited.",
        gtm=["Cold email to D2C brands (Shopify India list)", "Partner with Shopify, Instamojo", "Instagram outreach to brands", "Content: 'Reduce support costs with AI'", "Free for first month"],
        risks=["Tidio, Intercom, Drift exist (but expensive)", "Customers hate chatbots ('I want human')", "Accuracy needs to be high (wrong info = customer loss)", "Regional language quality variable"],
        advantage="India pricing. Indian e-commerce nuances (COD, Tier-2 city shipping). You can offer hybrid (AI + human). Rapid iteration on accuracy.",
        domain_id="customer_support", pain=8, weeks=3, market=9, complexity=6
    ),
    create_idea(
        id="support_article_rec",
        title="Support Article Recommendation Engine",
        problem="SaaS companies have 50-200 support articles. Customers search, don't find answer (poor search). Submit ticket. 40% of tickets answerable by existing articles. Support team sends article links manually.",
        target="SaaS companies, B2B service companies. Decision maker: Support Lead / Product Lead.",
        ai="Semantic search over support articles. 'Did you mean?' suggestions. In-product contextual help (show relevant article based on page). Analytics: which articles helpful, which need improvement.",
        mvp=["Ingest support articles (from Zendesk, Intercom, or docs site)", "Semantic search (vector similarity)", "Search widget for website", "Contextual suggestions (based on current page)", "Analytics dashboard"],
        tech=["Text embedding (OpenAI ada-002 or sentence-transformers)", "Pinecone/Qdrant free tier", "FastAPI backend", "React search widget", "Next.js dashboard"],
        moat="Contextual suggestion quality. Integration with support platforms. Analytics on article effectiveness.",
        pricing="₹4999/month for <100 articles. ₹9999/month for 100-500 articles. Enterprise: ₹29,999/month + unlimited.",
        gtm=["Cold email to Support Leads", "Partner with Zendesk, Intercom", "LinkedIn outreach", "Post in SaaS communities", "Free trial: 30 days"],
        risks=["Algolia, Elasticsearch have semantic search (but complex setup)", "Support platforms adding AI search (Zendesk AI)", "Low perceived value ('We have search already')", "Requires good articles (garbage in, garbage out)"],
        advantage="You can integrate with Indian SaaS tools (Zoho, Freshdesk). Simple setup (not over-engineered). Rapid iteration on search quality.",
        domain_id="customer_support", pain=7, weeks=2, market=7, complexity=5
    ),
    create_idea(
        id="support_macro_lib",
        title="Support Macro Library with AI Suggestions",
        problem="Support agents use macros/templates for common responses. Finding right macro = search through 50-100 templates. Copy-paste, manually customize. 2-3 min per ticket. New agents struggle (don't know which macro).",
        target="Support teams (10-100 agents). Decision maker: Support Lead.",
        ai="Analyze ticket content. Suggest top 3 relevant macros. Auto-fill customer-specific details (name, order ID). Learn from agent selections (improve suggestions).",
        mvp=["Integration with Zendesk, Freshdesk", "Macro library (import existing macros)", "AI suggestion (show top 3 when agent opens ticket)", "One-click insert", "Analytics: most-used macros, agent time saved"],
        tech=["Zendesk/Freshdesk API", "Text embedding for macro matching", "GPT-4o-mini for personalization", "FastAPI backend", "Chrome extension for UI"],
        moat="Learning from agent behavior. Integration depth. Personalization quality.",
        pricing="₹999/agent/month. 10-agent team = ₹9,990/month. Annual: 20% discount.",
        gtm=["Cold email to Support Leads", "Partner with Zendesk, Freshdesk", "LinkedIn outreach", "Case study: 'Reduced response time by 40%'", "Free trial: 1 month"],
        risks=["Zendesk has macro suggestions (but basic)", "Requires many macros to be valuable (50+)", "Agent adoption friction (learning new tool)", "Per-agent pricing expensive for large teams"],
        advantage="You can customize for Indian support language (Hinglish). Simple UI (not over-engineered). Rapid iteration on suggestion quality.",
        domain_id="customer_support", pain=7, weeks=3, market=6, complexity=5
    ),
]
